[package]
name = "v2f"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.23", features = ["derive"] }
deflate = "1.0.0"
serde = { version = "1.0.215", features = ["derive"] }
