match_arm_blocks = false
hard_tabs = true
max_width = 100
indent_style = "Visual"
force_multiline_blocks = true
format_code_in_doc_comments = true
match_block_trailing_comma = true
imports_granularity = "Item"
group_imports = "One"